# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
[[main]]
  name = "Home"
  url = "/"
  weight = 10
  
  name = "Brief About Us" 
  identifier = "about-us"
  weight = 20

  name = "Current Projects"
  identifier = "projects"
  weight = 10

  name = "Success Stories Highlights"
  identifier = "projects" 
  weight = 10

  name = "Partners"
  identifier = "our-partners"
  weight = 10


  [[main]]
  name = "About Us"
  url = "/about-us"
  weight = 20

  [[main]]
  name = "Projects"
  url = "home/projects"
  weight = 30

[[main]]
  name = "Media Center"
  url = "post"
  weight = 40

  [[main]]
  name = "Support/Join Us"
  url = "donate"
  weight = 50

[[main]]
  name = "Contact Us"
  url = "contact"
  weight = 60

# [[main]]
#  name = "Blog"
#  url = "blog"
#  weight = 20

#[[main]]
#  name = "People"
#  url = "people"
#  weight = 30


#[[main]]
#  name = "Events"
# url = "event"
# weight = 40

#[[main]]
#  name = "Talks"
#  url = "talks"
#  weight = 41

#[[main]]
#  name = "Publications"
#  url = "publications/"
#  weight = 50

[[main_right]]
  name = "Courses-"
  url = "courses/"
  weight = 70


#[[main]]
#  name = "Slides"
#  url = "slides/slides"
#  weight = 80

[[main_right]]
    name = "Tutorial"
    url = "Tutorial"
    weight = 80


  # Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/media/resume.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "media/resume.pdf"
#    weight = 80
