  [[main]]
    name = "Home"
    url = "/"
    weight = 10

  [[main]]
    name = "Tags"
    identifier = "tags"
    weight = 20

  [[main]]
    name = "Academic"
    parent = "tags"
    url = "tags/academic/"
    weight = 10

  [[main]]
    name = "About Us"
    url = "#about-us"
    weight = 20

  [[main]]
    name = "Projects"
    url = "#projects"
    weight = 30

  [[main]]
    name = "Media Center"
    url = "post"
    weight = 40

  [[main]]
    name = "Support/Join Us"
    url = "donate"
    weight = 50

  [[main]]
    name = "Contact Us"
    url = "contact"
    weight = 60

[[main_right]]
  name = "Courses"
  url = "courses/"
  weight = 70

[[main_right]]
  name = "Tutorial"
  url = "Tutorial"
  weight = 80
